AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: CodeGuardian - Autonomous Security Agent

Globals:
  Function:
    Timeout: 900
    MemorySize: 1024
    Runtime: python3.12

Resources:
  CodeGuardianFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: CodeGuardian-Agent
      CodeUri: package/
      Handler: lambda_function.lambda_handler
      Description: Autonomous security analysis agent using Bedrock
      Environment:
        Variables:
          AWS_REGION: us-east-1
      Policies:
        - AmazonBedrockFullAccess
      Events:
        ApiEvent:
          Type: Api
          Properties:
            Path: /analyze
            Method: post

Outputs:
  CodeGuardianApi:
    Description: API Gateway endpoint URL
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/analyze/"
  CodeGuardianFunction:
    Description: Lambda Function ARN
    Value: !GetAtt CodeGuardianFunction.Arn
